hash-format = "sha256"

[[files]]
file = ".envrc"
hash = "1d26c74fd25a4c3dbb09e029fc609588da499fd4af2a41c88f6316c7f8c54cf1"

[[files]]
file = "flake.lock"
hash = "c45a86fb427e6174d8223849009d9b584ba460804f43c0b5d17db2aac0b85369"

[[files]]
file = "flake.nix"
hash = "dde7a6053d301323754c71b8948e95e6c8bfe1a31f70c4140021452175ab4aff"

[[files]]
file = "mods/accessible-step.pw.toml"
hash = "297e887556ead53d8ddfa837903655478c5c1988a69d156e313f81e5db858f3e"
metafile = true

[[files]]
file = "mods/additional-lanterns.pw.toml"
hash = "347903b32b7f59fbad4208eac209d82f4f42962dcfd971e2ddd3dba3f36f5027"
metafile = true

[[files]]
file = "mods/additional-placements-fabric.pw.toml"
hash = "75a93c3274d09ff7f6456c7bfa35a4bdd53faee235be6cb28ebdf1cb0966a4cd"
metafile = true

[[files]]
file = "mods/additionalbars.pw.toml"
hash = "a903c84b0a7cb7abc14ea5f9bfb93b4677c5bc89174534b7f7aea88300391af9"
metafile = true

[[files]]
file = "mods/adventure-protect.pw.toml"
hash = "26a34f00454d0c4486486986be470562dd3c479ea88ca55f6a6b89e52fb97844"
metafile = true

[[files]]
file = "mods/aesthetic-frames.pw.toml"
hash = "3ea23480ac93c39def1df964c2da9ab9dc0d499d42b093be86004b307abd35f8"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "d4838d91cd7747816ade0f2f4a46c701a53c3ef84cb278ec24e8f6fb828a85c3"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/asahi.pw.toml"
hash = "830f9c2e949dec3a15b3d2b3e44dbdea5dc29260f385996a23968cc25daf2e88"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "5601649308a7d9f1658a942bbd48d3bd899a81fabd4ea1296952b48474d1ee1d"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "fff0b46fc8b9e9c44f4b6af6ce8c90d12e79b955506f6884986647011d92abc6"
metafile = true

[[files]]
file = "mods/axiomtool.pw.toml"
hash = "e095b86ace2ba079e80dbc188be0f3f7f750d49f0113a3d6c77dd3e3f931d54f"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "39f761298d831e49308b1507c2ac1e524f4ad07f220621e45290c810deb1c497"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "6e39e7712a94830fbc2bd0b6ec73e03f54de5edfcca85da6e89a0021e9a3bf1a"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "e53155acc7b3692b6a2684f6334d50c9e128b1f007ad7b2c8b514e7d1f2500c5"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7d1815ec4f2098c4de8b01494373d84da8a5104accd5ae028a2a020595646082"
metafile = true

[[files]]
file = "mods/bindcommands.pw.toml"
hash = "5415fce09d97ccfce24ab9da8090128868e87ad51e3418a6cf84d7c90831d679"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "8bc168948c5f92a10252f12ad4f41caeefbe508f0326fc4185217d60c4cb2292"
metafile = true

[[files]]
file = "mods/book-and-quick-save.pw.toml"
hash = "a1dbb9946dc46c3953f6b3ac64ae0588038c8011aba8f47617f64d8ab66d430d"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
hash = "40b83a8a937cb59b667c229dfa541f9a7badf8c34fa7e301b2b2b9f4df6a5e2a"
metafile = true

[[files]]
file = "mods/camerapture.pw.toml"
hash = "3cc79a406a67f07707ed8676b1b5786d2112547dca4df21757ea5e54c7cfe72d"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "bbff83f5167e56b5cfd947b314b3193110d94425c2f45b385e19624a7c5346ef"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "d3c63f438a007fc0615987f1cc2108e240a61c22a21ef643912e8591352a417f"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "a4d21da45c40e8f1e3b76c9855ea3f1c15736cf2b12475e9de3efd05f8f48a8d"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "7fe287ca1bed0ad67f37e62a5816da7b7ae59486102c5e4b7532f0a999444527"
metafile = true

[[files]]
file = "mods/client-vein-miner-reworked.pw.toml"
hash = "5c59bc531581dbcff77071246d611ad00b7ce46987c11d3466c34db3114a6385"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/coloredwater.pw.toml"
hash = "e641fd2c316161c54e15e10f45625ebb3f2bf7f8489d9cbe2594fb869ef77b83"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "b5bdeb1177654fc3914be329612778078231cd3dc1b9157669c641c905146690"
metafile = true

[[files]]
file = "mods/connected-glass.pw.toml"
hash = "8d1340abed5132384623f395abe4485bdfccc515008c204f85a4205c81755ff5"
metafile = true

[[files]]
file = "mods/connectiblechains.pw.toml"
hash = "e28f40d34c30c32d4bd05cfb80215c907b59e43d7e593ead73b3a04bb959bd4a"
metafile = true

[[files]]
file = "mods/construction-wand-fabric.pw.toml"
hash = "dd739f3873de08e81f7a519a2a89e58ce34b44f308eb25e92ca1cc50bea31cd8"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "eecdc8127f69c74ff55fd183d1f1d7d5ef3e714d73845a239fe9e086147a67b1"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "23b3bf6d1931acd2aa6daa5409b274b0d4ec9ec659c01d11454093d8fcd1e342"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
hash = "33c41ce33262edd33832faac7b18119f356ab55352e74fc89f58c13a856cabce"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
hash = "2bcdcf72c50d93ef010c8895ad1588baf9181612dcbdd05a2a870ff88bc34649"
metafile = true

[[files]]
file = "mods/dramatic-doors.pw.toml"
hash = "7b9204de0626ccbcb91201c16427cf5bc70e5990e35fe553d4709794f3b21776"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "149aa4939d024ae412427ea7b7212cd6553b03839149f7cf102bd19a48647da3"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4effaea1cdc0ccd0de4a94ab435cc3cb22085933fca7e1dd35b9fb8953a1ce9e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "60e6720aafdfa3304b086f7465917179485a3b2463230505728bd24d54113de3"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "135837201d4c30811971e630e957867397b995e6803ff75754d510bf1b4fe8fc"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
hash = "5c1b16bbf2308c87c81a713cac4b2e6c6796e854d5133281c759759375e02d94"
metafile = true

[[files]]
file = "mods/essential.pw.toml"
hash = "e70f33263672a6110ae5845dd6fef356999cd500ca75fff2a7c609101da6beda"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
hash = "a80c982a4c953f3c214ab652dec5e603aec4e937fd1f3b3b2920b5859ba4ca1f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "94f000249d21c4fc3b7744f9579bb6ac0d48e6bf4860fad16f23c997950a47f3"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "1157104e93eab88b9d3c864fe5efea64497c6c4d5614aaa370a96e94a850014b"
metafile = true

[[files]]
file = "mods/fastboot.pw.toml"
hash = "b76c5a17f55ed633c0e61518f6078b5585a655680744681da11557ce5f5d0089"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "d0e586bf4b4f9f003b1de1a3e18f67540233a0295b487009047056198f694f0f"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
hash = "92a3854c609a52101fe1c702b9b7b52a98a395d54493872ba06f97120d50b5b3"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "2e705f04feb06d4340c59aebe8430c79a48635f6cd40b5c9f9ea7e4e6500721a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "ae2dd2b605e120ec04be2accfeb20938ceb4551bcc683b8c1a0f725578ea293e"
metafile = true

[[files]]
file = "mods/gk1h-core.pw.toml"
hash = "97c2d23b498e967a310a892cc576adab7cecd6b5b3a1427de172fe1a95784aa4"
metafile = true

[[files]]
file = "mods/gk1h-extras.pw.toml"
hash = "910ac8232506828047a32b3202ce72fbe2113283830e3d843da41304fad7fb85"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "2600fb5f2efa6dffd1bcc04eea4c2646c101da4320da0c88d5616d5c2f41a439"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "907ed71a8d572d5bc2a8f956b0b0d0fad37e1d5bdd48464041a76ef8fca79cb7"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "26c8dc0356db71c54d5f51372932da38f42ce769a619b928b80fcb2a54d9e719"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "7cae98a677565da83a0f0dd38a3e6d573cc4388912c20d8ff43c48ec6fa59bc5"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "80858e1b1477432110b72aab33348635139d6e8fe7bc05db3ba00651de635720"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e40ab1a8992d800199a6ac5a1a7411bae8141817f645c82c1fdc8c1381393f9e"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
hash = "250a60ad345454a739a4ed90779501c31c90f5be387c3e52816ced6713012e98"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "34d75daff8b8260780d97bbc2dc545739399df1d5ac304eeb2f80e23354cf3af"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "f5f134844b199b78f07b6f58ded80ee7b6a786d509a95687a2abb48e8dffee6b"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "f48382dc8ad6b473ed5e6d050038513e56697143b1232c1ae8ff40861f06ba2f"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "93c57990c9353797107ca22b047d3ca732a977b0cfd343a0fb6a70f80649e282"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "99deb2f3aa9cd5d7eff3dd58e8acbb32662cbd448a10fd588c166786200e3019"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
hash = "07a1c8305abb42f00b4ea3f3470990e0c59275d4a4c450d7d5cb3ad77870a714"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "288747beb2483e473a86de31a9fff544e398d37e661c4a9bb7aa16769f7ee8f5"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
hash = "4797458bb275c5e9c3657e353ae598ab38e07e3386092a0c13f27448bef3ddd3"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "1197c76400a13a3961f70538d7acf7764436fc92899cca5bd05b9bf3027601c2"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "8d4ecc66f120419b4bc09fdd14151d2a207ddec30b46ae2184300fec0031b092"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "b298c392b78418707ae9a32e2cf0af27ea9e57a0a673b895012dc90d08b73157"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "70ec6df06813b68cf3082c5a52339d32397c200f6acc8c02170453200bd79165"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "b7efdf14e315ce387de72feb5337e84f96725d6d1c7e4f4cce5d444a75c2da3e"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d9221689ffa47dcd27e6c0590ba7b3227f83d48a6e9592cd09e1835f143d793a"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "2e26dd4ebd07b97d68a9775b84fae707d8824c926e086bb3bcad11687b3fb204"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "f77a1de001da650d5745acd2b410d6729bf61282d91cf3e8883e891f9707f85a"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6be43ffc708ac329843aee99ededc692ecf6461ee8e409d373f55fc5494db5af"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/music-maker-mod.pw.toml"
hash = "ae1db16c78063c935e6e2f6cb6b0bab95d97bb8955c0e26f36abfbdf98a52e20"
metafile = true

[[files]]
file = "mods/namer-scoreboards.pw.toml"
hash = "01152e874ee1e555aafafea421f4da4b418acf642ae1cf5b34dc6b81775aae8f"
metafile = true

[[files]]
file = "mods/nbt-copy.pw.toml"
hash = "7a436f1e57436719f8181e010bd8cc7565472661fb49aaeb2ea7f5f0d88b052c"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "c0969cf2bc2301c45c2bfcfc31a7132aad2bfbc893b340e804116dd6a3843f0b"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "62df1cb449d5c6f8c5d670f14819a106a451e88102b8b066efeb73951f058d30"
metafile = true

[[files]]
file = "mods/polysit.pw.toml"
hash = "2b6e1038d6a1082196fe3a1fe18e55d35f2a42cd99b9158c9ede510012112af3"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "a717ad1dd50748d87bb8a1126054933bf59617238f968acaa1844e71aed29585"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d3f633dd12cd039a4e58dd398d1c80a324b0d78b9da5b3972b69640bfed211ed"
metafile = true

[[files]]
file = "mods/scoreboard-helper.pw.toml"
hash = "60c254b81078aacb9385ff86b5baf385bcbc13a9e308a87edeb9c12572be20d9"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "8302da862578554b012b2cfe58a3c1e75b514d09f94d842e7303be41a2157aeb"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "272b27d64cd27b909567437683287909b35de9f78db27214efb1d5e4334f9f82"
metafile = true

[[files]]
file = "mods/sodium-device-check.pw.toml"
hash = "5129f6db6b161aa9aa08afaf8e0db270a3b252df2b24701762d5353810929a1a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "0a6179657082b15117e18fbc80fd60538dc91024a63006e843cb5dbf1991bcbe"
metafile = true

[[files]]
file = "mods/spiffyhud.pw.toml"
hash = "cbceaf76cb0586ce581d0946096ba85743c443d38b075b51c2c823bf72335ba7"
metafile = true

[[files]]
file = "mods/stone-zone.pw.toml"
hash = "c845f99df1c99e50fd2cc77db09be16b9b04a389616fa11bf3cbdaab4c1d5eb2"
metafile = true

[[files]]
file = "mods/stoneworks.pw.toml"
hash = "53ff34a5821f588c428221b6e7104d3e4fcf70ab7683c241e4149a4816251fed"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "97df1677b1871339d75f5244c74446990a6109186f3b0478961181352b23ad8d"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
hash = "6e42988e60a32a17a6bf9d7f7176911fa1d5093d814d35eb0c62c00318f0b341"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "d3f1d02d785b5dd6d53ab6b38a903558b36e1e97dfb4e64b76375c75e26e90bb"
metafile = true

[[files]]
file = "mods/talkingheads.pw.toml"
hash = "ac95d53b0b70d757866a88623be21643fb81a2e1b449c1153f765111d390dcae"
metafile = true

[[files]]
file = "mods/templates-2.pw.toml"
hash = "55de3aa867841af02dc02b83983de55917f99237a6def88736bb556903aad5ad"
metafile = true

[[files]]
file = "mods/visible-ghosts.pw.toml"
hash = "57d15dc9d7fea5c1863bed5656ad67a645f96d5aefbeb845ef99225cf23ad59c"
metafile = true

[[files]]
file = "mods/void-block-fabric-1.21.1.pw.toml"
hash = "bf44125fbfd253ee0c9eb50092869f726a1b9daacc6e7a951b441d2ba6cd8dce"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "08d4775f8546564ad812b09062633ffc48f44b76328efe3832c021651af86b14"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8ffa4ba1466882a5abef6c6d220824f1ce4e228771f854f19e4fceb80598723c"
metafile = true
