name = "Joelbotc"
author = "joel48"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "997e3974156a47b66ea3c43e623220f945aecf2976f06e660f5c5b472458799a"

[versions]
fabric = "0.17.0"
minecraft = "1.21.1"
